name: Release
on:
  push:
    branches: main

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          python-version: "3.8"
      - name: Build
        run: |
          sudo apt update
          sudo apt install build-essential -y
          sudo apt install python3-pip -y
          sudo apt install patchelf -y
          pip3 install -r requirements.txt
          sh ./build.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./dist/ghemoji
